### PR TITLE
restructure the files and classes

### PR DESCRIPTION
**Pull request by scrooloose**
- move the files into a `lib` directory
- split the classes out of the main rogue.py file into one class per
  file under the lib/rogue dir
- put the constants into lib/rogue/constants

---

Hey, I see this is a learning project and I'm new to python so it seemed like a good idea to check it out :)

My changes are purely refactoring with no functional differences (that I intended anyway!). Feel free to reject or request amendments or otherwise rip the shit out of my changes :)

### CODE REVIEW

**Comment by r1chardj0n3s** [comment]
I argue against this change. The project is intended to be extremely simple and straight-forward. Hiding the most important file away in a directory does not help that. The rogue.py file should be at the root of any checkout or distribution of this code.

It is actually for this reason that I was going to argue for moving the contents of trunk/rogue into the root of the repository.

**Comment by scrooloose** [comment]
Im new to python, and am basically applying the directory layout conventions from ruby :)

Is there another convention in python? I did some brief looking around before submitting this pull request and didnt see a clear convention.

**Comment by r1chardj0n3s** [comment]
Conventions are all well and good, but in this case I think being friendlier to noobs is the highest priority. In my opinion hiding the code away in a directory called "lib" is obscuring things unnecessarily. Sure I recommend that approach to people who know what they're doing, but I think it's OK to break that rule for this project given the audience.

**Comment by IanWitham** [comment]
In my experience directory conventions usually only show up in Python when there is a framework involved with some requisite boilerplate, eg Django. PyGame doesn't really have much enforced boilerplate. I would agree for this project where readability and "noob friendliness" is a chief design goal directory conventions can take a back seat.

**Comment by kcunning** [comment]
Okay, finally found time to comment on this.

Later on, I might offer a branch that includes more files. I've found with beginners, though, giving them a ton of folders and files only adds to the confusion. So, for now, closing this :)

**Pull request closed without merging**
